version: "2"
services:
  facecard:
    image: gooa.cc/facecard:latest
    command: sh bin/start_from_docker.sh
    ports:
      - "8088:8088"
    environment:
      JAVA_ENV: dev
    container_name: facecard
    restart: always
